CREATE TABLE "DEMO"."PLAYER"
   (	"PLAYER_ID" NUMBER(6,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"AGE" NUMBER(3,0) NOT NULL ENABLE,
	"MATCHES" NUMBER(3,0) NOT NULL ENABLE,
	 CONSTRAINT "PLAYER_PK" PRIMARY KEY ("PLAYER_ID")
     )